#!/bin/bash

set -eu # -x for verbose logging to juju debug-log

umask 002

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/local"
app_user=`config-get app_user`
app_port=`config-get app_port`
app_node_env=`config-get app_node_env`

cd ${app_dir}
sudo npm update && sudo npm install

chown -Rf ${app_user}.${app_user} ${app_dir}

service ${app_name} restart
