#!/bin/bash

set -eu 

# Get the database settings; if not set, wait for this hook to be
# invoked again
host=`relation-get private-address`
if [ -z "$host" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

host_service_name=`echo $JUJU_REMOTE_UNIT | sed -e 's|/.*||'`

relation_port=`relation-get port`
port=${relation_port:-27017}

replset=`relation-get replset`

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/local"

config_auth_host() {
  config_file_authorizations=$app_dir/node_modules/site-data/node_modules/site-auth/config/conf.js
  config_file_user_details=$app_dir/node_modules/site-data/node_modules/site-user/config/conf.js
  
  sed -i "s/mongo_host.*/mongo_host\" : \"${host}\"/" $config_file_user_details
  sed -i "s/mongo_port.*/mongo_port\" : ${port}/" $config_file_user_details
  #sed -i "s/mongo_replset.*/mongo_replset\" : \"${replset}\"/" $config_file_user_details
    
  sed -i "s/mongo_host.*/mongo_host\" : \"${host}\"/" $config_file_authorizations
  sed -i "s/mongo_port.*/mongo_port\" : ${port}/" $config_file_authorizations
  #sed -i "s/mongo_replset.*/mongo_replset\" : \"${replset}\"/" $config_file_authorizations
}

config_app_host(){
  config_file_blog=$app_dir/node_modules/site-data/node_modules/site-blog/config/conf.js
  config_file_project=$app_dir/node_modules/site-data/node_modules/site-project/config/conf.js
  
  sed -i "s/mongo_host.*/mongo_host\" : \"${host}\"/" $config_file_blog
  sed -i "s/mongo_port.*/mongo_port\" : ${port}/" $config_file_blog
  #sed -i "s/mongo_replset.*/mongo_replset\" : \"${replset}\"/" $config_file_blog
  
  sed -i "s/mongo_host.*/mongo_host\" : \"${host}\"/" $config_file_project
  sed -i "s/mongo_port.*/mongo_port\" : ${port}/" $config_file_project
  #sed -i "s/mongo_replset.*/mongo_replset\" : \"${replset}\"/" $config_file_project
}

configure_app() {
  juju-log "configuring ${app_name} to work with the mongodb service"


  juju-log "Writing $app_name mongodb config files."
  if [ == 'auth-db']; then
    config_auth_host
  elif[host_service_name == '${app_name}-db' ]
    config_app_host
  fi

  app_port=`config-get app_port`
  open-port $app_port/TCP
}
configure_app

juju-log "(re)starting app"
service ${app_name} restart || service ${app_name} start
