#!/bin/bash

set -eu 

# Get the database settings; if not set, wait for this hook to be
# invoked again
host=`relation-get private-address`
if [ -z "$host" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

relation_port=`relation-get port`
port=${relation_port:-27017}

replset=`relation-get replset`

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/local"

configure_app() {
  juju-log "configuring ${app_name} to work with the mongodb service"

  config_file_authorizations=$app_dir/node_modules/site-data/node_modules/site-auth/config/conf.js
  config_file_user_details=$app_dir/node_modules/site-data/node_modules/site-user/config/conf.js

  if [ -f ${app_dir}/Procfile ]; then
    cat > /etc/juju_nodejs_app_${app_name}_mongodb.env <<EOF
{
  "host": "${host}"
, "port": ${port}
, "replset": "${replset}"
}
EOF
    MY_DIR=`dirname $0`
    $MY_DIR/config-changed
  else
    juju-log "Writing $app_name mongodb config files."
    
    sed -i "s/mongo_host.*/mongo_host\" : \"${host}\"/" $config_file_user_details
    sed -i "s/mongo_port.*/mongo_port\" : ${port}/" $config_file_user_details
    #sed -i "s/mongo_replset.*/mongo_replset\" : \"${replset}\"/" $config_file_user_details
    
    sed -i "s/mongo_host.*/mongo_host\" : \"${host}\"/" $config_file_authorizations
    sed -i "s/mongo_port.*/mongo_port\" : ${port}/" $config_file_authorizations
    #sed -i "s/mongo_replset.*/mongo_replset\" : \"${replset}\"/" $config_file_authorizations
  fi

  app_port=`config-get app_port`
  open-port $app_port/TCP
}
configure_app

juju-log "(re)starting app"
service ${app_name} restart || service ${app_name} start

